# Generated by Django 4.1.3 on 2022-11-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_update', models.DateTimeField(auto_now=True, null=True)),
                ('gmt_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(help_text='库的名称，一个库可能有多个实例。最大长度：64字节', max_length=64, unique=True, verbose_name='数据库名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='数据库创建时间', verbose_name='数据库创建时间')),
            ],
            options={
                'verbose_name': '库表',
                'db_table': 'db_schema',
            },
        ),
    ]
