# Generated by Django 4.1.3 on 2022-11-23 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_update', models.DateTimeField(auto_now=True, null=True)),
                ('gmt_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('task_id', models.CharField(max_length=128)),
                ('task_name', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=64)),
                ('result', models.TextField(max_length=65535)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='waiting', max_length=32)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstanceModel',
            fields=[
                ('gmt_update', models.DateTimeField(auto_now=True, null=True)),
                ('gmt_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('host_ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('role', models.CharField(choices=[('master', 'master'), ('slave', 'slave')], max_length=64)),
                ('status', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('pending', 'pending')], default='online', max_length=64)),
                ('schema', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='dbms.schemamodel', to_field='name')),
            ],
            options={
                'verbose_name': '实例表',
                'db_table': 'db_instance',
            },
        ),
    ]
